In [1]:
import numpy as np



In [2]:
class Madaline(object):
    def __init__(self,ni,nh):
        self.no_of_inputs= ni
        self_no_of_hidden_layers = nh
        self.learning_rate = 0.5
        
        self.X = np.array([[1, 1, 1, -1], [1, 1, -1, 1], [1, -1, 1, 1], [1, -1, -1, -1]], dtype = float)
        
        #number of nodes in each hidden layer 'nodes_hidden[]'
        self.nodes_hidden= [] 
        for i in range(nh):
            print("Enter the number of nodes in hidden layer ", i+1)
            self.nodes_hidden.append(int(input()))
        #print(self.nodes_hidden)
        
        # Weights from Input to first hidden layer
        self.Wih = np.random.rand(self.no_of_inputs, self.nodes_hidden[0])
        self.Wih = np.around(self.Wih, decimals = 3)
        print(self.Wih)
        
        print("")
        
        #Weights from hidden to hidden layers
        
        self.Whh = []
        for i in range(nh-1):
            a = []
            for rows in range(self.nodes_hidden[i+1]):
                b = []
                for cols in range(self.nodes_hidden[i]):
                    b.append(float(np.random.random()))
                a.append(b)
            self.Whh.append(a)
        
        for i in range(nh-1):
            self.Whh[i] = np.around(self.Whh[i], decimals = 3)
            print(self.Whh[i])
        
        
        #Weights from last hidden layer to the output layer
        print("")
        
        # np.random.rand : generates floating point random number b/w 0 and 1
        self.V = np.random.rand(self.nodes_hidden[nh-1]+1, 1)
        self.V = np.around(self.V, decimals = 3)
        
        print("")
        print("Final Output:")
        print(self.V)
        print("")
        
        

print("Enter the number of Inputs: ")
ni = int(input())
print("Enter the number of nodes in hidden layers: ")
nh = int(input())    
print("")
M =Madaline(ni, nh)
                                    
        

Enter the number of Inputs: 
3
Enter the number of nodes in hidden layers: 
2

Enter the number of nodes in hidden layer  1
3
Enter the number of nodes in hidden layer  2
4
[[0.062 0.659 0.667]
 [0.874 0.384 0.764]
 [0.303 0.009 0.052]]

[[0.071 0.801 0.889]
 [0.865 0.613 0.614]
 [0.011 0.681 0.435]
 [0.143 0.276 0.298]]


Final Output:
[[0.771]
 [0.017]
 [0.243]
 [0.613]
 [0.796]]

